### PR TITLE
a small typo in renviron file location + structure

### PR DESCRIPTION
**Pull request by jlacko**
First of all: thanks for a great package, strange that something like this was not done yet... It is 2023 for Pete's sake :)

Secondly: I had slight issues with storing my login creds in the  `.Renviron` file, nothing truly serious: extra space in filename and single quotation marks as string separators. It made the crash go away...

Thanks again!

### CODE REVIEW

**Comment by kalab-oto** [comment]
Thank you! Its my first package :). Its improved port from my older QGIS plugin and following python library. It makes more sense since R is much more widespread than python in ecology.

Yes, the login store was wrong, thank you. It maybe could causes crashes in some logins and passwords, not my case so I didn't notice :)

But I just don't understand why `Sys.sleep(3)`, because at that time all infomrations are stored in `filter_page` and next request always works fine. Its just being polite :) or am I missing something?

**Comment by jlacko** [comment]
Congrats on your first package then! The first one is always special.

The creds store was more of an issue, as it led to crashes (that is how I found out, wink wink).

The sleep was more of a suggestion, as the `ndop_search()` function behaved strangely for me. I kept getting `NA_Real_` for number of records, leading to all sort of bad results down the line.
I did not have time to debug it thoroughly, but it seemed to me that the root cause was that the content did not finish loading by the time it was processed; I have noticed issues like this in API wrapping functions.
It could be that this is why you call the API twice - which I noticed, but did not really dwell upon. Feel free to reject the wait, as I said it was more of a suggestion than an issue.

**Comment by kalab-oto** [comment]
Yes, the for loop is workaround and I will fix it (https://github.com/kalab-oto/rndop/issues/6), but I think its unrelated. I Merge it as it is and test it further, and maybe remove it later.

Anyway, thanks a lot for testing!

**Comment by kalab-oto** [comment]
If you mean the dates that is in the table, then that is on purpose, I wanted to keep the raw data so that it is the same as when someone downloads it via the web, so it can be used already in established processes. But I plan to add an argument that will return the modified table (or it will be default, and the argument will be for the raw table, maybe this will be better). I plan return dates separately, year, month and day, and a column as Date class, and some other stuff. A lot of work to think about :D

**Comment by jlacko** [comment]
I knew it! It seemed too obvious to be just coincidence. I rest my case :)

**Pull request merged**
